In [5]:
#read library packages
import pandas as pd #reading dataset and computing statistic
import seaborn as sns #this line is for visualisation

In [6]:
#read the dataset
df=pd.read_csv('meanloan.csv')

In [7]:
df.head()

,Year,Description,Borrower_Type_Code,Borrower_Type_Description,Characteristic_Type,Unit,Observation_Amount
0,2016,Average Loan-to-Value,FTB,First Time Buyers,Loan Information,Per Cent,78.8
1,2016,Joint Applicant,FTB,First Time Buyers,Borrower Information,Per Cent,67.1
2,2016,Fixed,FTB,First Time Buyers,Share of Lending: Interest Rate Fixation Type,Per Cent,55.5
3,2016,Average Loan Term,FTB,First Time Buyers,Loan Information,Years,29.0
4,2016,Average Loan Size,FTB,First Time Buyers,Loan Information,Euro,189739.0

In [8]:
df.isnull().sum()

Year                         0
Description                  0
Borrower_Type_Code           0
Borrower_Type_Description    0
Characteristic_Type          0
Unit                         0
Observation_Amount           0
dtype: int64

In [10]:
# Split dataset in features and target variable
feature_cols = ['Year', 'Description', 'Borrower_Type_Code', 'Borrower_Type_Description', 'Characteristic_Type', 'Unit', 'Observation_Amount']
X = df[feature_cols]               # Features of the dataset
y = df.Description                 # Target variable of the dataset

# X = pima.iloc[:, :-1]              # All rows, all columns except the last
# y = pima.iloc[:, -1]               # All rows, only the last column

# X = pima.iloc[:, 0:8]
# y = pima.iloc[:, 8]

# Display the X and y arrays
print(X, y)

     Year              Description Borrower_Type_Code  \
0    2016    Average Loan-to-Value                FTB
1    2016          Joint Applicant                FTB
2    2016                    Fixed                FTB
3    2016        Average Loan Term                FTB
4    2016        Average Loan Size                FTB
..    ...                      ...                ...
375  2025                   Dublin                SSB
376  2025  Leinster (excl. Dublin)                SSB
377  2025                  Munster                SSB
378  2025                 Connacht                SSB
379  2025                   Ulster                SSB

        Borrower_Type_Description  \
0               First Time Buyers
1               First Time Buyers
2               First Time Buyers
3               First Time Buyers
4               First Time Buyers
..                            ...
375  Second and Subsequent Buyers
376  Second and Subsequent Buyers
377  Second and Subsequent Buyers
378  Second and Subsequent Buyers
379  Second and Subsequent Buyers

                               Characteristic_Type      Unit  \
0                                 Loan Information  Per Cent
1                             Borrower Information  Per Cent
2    Share of Lending: Interest Rate Fixation Type  Per Cent
3                                 Loan Information     Years
4                                 Loan Information      Euro
..                                             ...       ...
375                       Share Of Lending: Region  Per Cent
376                       Share Of Lending: Region  Per Cent
377                       Share Of Lending: Region  Per Cent
378                       Share Of Lending: Region  Per Cent
379                       Share Of Lending: Region  Per Cent

     Observation_Amount
0                  78.8
1                  67.1
2                  55.5
3                  29.0
4              189739.0
..                  ...
375                39.4
376                27.4
377                21.7
378                 8.2
379                 3.2

[380 rows x 7 columns] 0        Average Loan-to-Value
1              Joint Applicant
2                        Fixed
3            Average Loan Term
4            Average Loan Size
                ...
375                     Dublin
376    Leinster (excl. Dublin)
377                    Munster
378                   Connacht
379                     Ulster
Name: Description, Length: 380, dtype: str

In [13]:
df.columns.tolist()

['Year',
 'Description',
 'Borrower_Type_Code',
 'Borrower_Type_Description',
 'Characteristic_Type',
 'Unit',
 'Observation_Amount']

In [20]:
df.describe()

              Year  Observation_Amount
count   380.000000          380.000000
mean   2020.500000        41136.793037
std       2.876068       109694.353196
min    2016.000000            0.500000
25%    2018.000000            9.800000
50%    2020.500000           34.400000
75%    2023.000000           90.200000
max    2025.000000       605528.000000

In [22]:
df.shape

(380, 7)

In [23]:
from sklearn.decomposition import PCA

In [28]:
df["Description"].unique()

<ArrowStringArray>
[  'Average Loan-to-Value',         'Joint Applicant',
                   'Fixed',       'Average Loan Term',
       'Average Loan Size',  'Average Property Value',
    'Average Borrower Age',   'Average Property Size',
                  'Ulster',                 'Munster',
 'Leinster (excl. Dublin)',  'Average Loan-to-Income',
       'Salaried Employee',                  'Dublin',
                   'Other',          'Average Income',
   'Average Interest Rate',                'Connacht',
                'Variable']
Length: 19, dtype: str